### ISSUE TITLE
Install instructions slightly unclear

### ISSUE THREAD

**Issue by dannycab** [mathpn/hoarder-miniflux-webhook#1]
I think the installation instructions are a little unclear.

I was able to get this to work by cloning the repo into my hoarder directory `/opt/docker-containers/hoarder` and then copying the appropriate information into a `.env` file, which I placed inside the cloned repo. 

Then, `docker compose build` and `docker compose up` ran fine. 

When I tried to use the repo itself (as suggested in the install), I kept getting errors that the `.env` file was not found.

Now this is working great!

**Comment by mathpn** [comment]
Thank you for the feedback! I've updated the README to make the installation instructions clearer. The key improvements include:

- Added explicit directory structure examples showing where files should be placed
- Clarified the location of the .env file and how to set it up

The updated documentation should make it easier for others to get the webhook service up and running. Please let me know if you encounter any other issues or if something still needs clarification!
